-- AlterTable
ALTER TABLE `notifications` ADD COLUMN `priority` ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT') NOT NULL DEFAULT 'LOW',
    ADD COLUMN `relatedEntityId` VARCHAR(191) NULL,
    ADD COLUMN `relatedEntityType` ENUM('USER', 'DEPARTMENT', 'TIMEOFF', 'TIMEENTRY', 'SCHEDULE', 'TIMESHEET', 'NOTIFICATION') NOT NULL DEFAULT 'NOTIFICATION';
