-- AlterTable
ALTER TABLE `notifications` ADD COLUMN `actionUrl` VARCHAR(191) NULL,
    ADD COLUMN `read` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `type` ENUM('MESSAGE', 'ALERT', 'REMINDER', 'UPDATE', 'ERROR', 'TIMESHEET_PENDING', 'TIMESHEET_APPROVED', 'TIMESHEET_REJECTED', 'SCHEDULE_UPDATED', 'SCHEDULE_CONFLICT', 'MISSING_CLOCKOUT', 'EARLY_LEAVE', 'OVERTIME_ALERT', 'DEPARTMENT_ADDED', 'DEPARTMENT_REMOVED', 'ROLE_UPDATED', 'SYSTEM_ALERT') NOT NULL;
