-- AlterTable
ALTER TABLE `time_entries` MODIFY `status` ENUM('NOTSUBMITTED', 'CANCELLED', 'PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `time_off_requests` MODIFY `status` ENUM('NOTSUBMITTED', 'CANCELLED', 'PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING';
